# .github/workflows/version.yml
name: Git Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure all tags are fetched

    - name: Get latest tag
      id: get_latest_tag
      uses: actions/github-script@v6
      with:
        script: |
          const tags = await github.repos.listTags({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 1
          });
          const latestTag = tags.data[0].name;
          core.setOutput('latest_tag', latestTag);

    - name: Display latest tag
      run: echo "The latest tag is ${{ steps.get_latest_tag.outputs.latest_tag }}"
